spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    username: ${nome_do_usuario}
    password: ${senha}
    url: "jdbc:postgresql://localhost:5432/ecommerce"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - aws-secretsmanager:/secrets/base_de_dados_ecommerce_v2
      - aws-secretsmanager:/secrets/chaves_de_seguranca_v2
      - aws-secretsmanager:/secrets/kms_id_v2
server:
  port: 8083

aplicacao:
  sqs:
    url: "ADD_SQS_URL" #adicione após subir a infra
  token:
    google-api:
      url: "https://oauth2.googleapis.com"
